# -*- coding: utf-8 -*-
"""TIMO_3_MG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAAaX3hS4Ojwy-ZY1lQ6x3gF9JbV4foj
"""

!pip install datasets

!pip install pytorch-lightning

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch
import torch.nn as nn
import numpy as np
import itertools
from sklearn.model_selection import train_test_split
import torch.optim as optim
from torchsummary import summary
import torch.optim as optim
import pytorch_lightning as pl
from PIL import Image
import wandb
from torchmetrics import Accuracy, F1Score, Precision, Recall
from torchvision import datasets, transforms
from datasets import load_dataset
from torch.utils.data import DataLoader, random_split, Dataset
import torchvision.transforms as T

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
trainset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
testset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

import torch
import torch.nn as nn
import torch.optim as optim
import pytorch_lightning as pl
from torchmetrics.classification import Accuracy, F1Score, Precision, Recall

class CNN(pl.LightningModule):
    def __init__(self,
                 kernel_size=(3, 3),
                 conv_filters=None,
                 num_classes=10,
                 lr=1e-3,
                 optimizer_cls=None,
                 optimizer_params=None,
                 batch_size=64,
                 dropout=0.5,
                 scheduler_params=None,
                 input_channels=3,
                 dense_layers = [240,60]):
        super().__init__()
        if conv_filters is None:
            conv_filters = [32, 64, 128]
        if optimizer_params is None:
            optimizer_params = {'weight_decay': 1e-4}
        if scheduler_params is None:
            scheduler_params = {'mode': 'min', 'factor': 0.1, 'patience': 3}
        if optimizer_cls is None:
            optimizer_cls = optim.AdamW
        self.dense_layers = dense_layers

        self.save_hyperparameters(ignore=['optimizer_params', 'scheduler_params'])
        self.optimizer_params = optimizer_params
        self.scheduler_params = scheduler_params


        layers = []
        in_channels = input_channels
        for out_channels in conv_filters:
            layers.append(nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, padding=1))
            layers.append(nn.BatchNorm2d(out_channels))
            layers.append(nn.ReLU())
            layers.append(nn.MaxPool2d(2))
            layers.append(nn.Dropout2d(dropout))
            in_channels = out_channels
        self.feature_extractor = nn.Sequential(*layers)


        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
        )
        cur_size = conv_filters[-1]
        for i in range(len(self.dense_layers)):
          self.classifier.append(nn.Linear(cur_size,dense_layers[i]))
          cur_size = self.dense_layers[i]
        self.classifier.append(nn.Linear(self.dense_layers[-1], num_classes))
        self.criterion = nn.CrossEntropyLoss()


        self.train_accuracy = Accuracy(task="multiclass", num_classes=num_classes)
        self.train_f1 = F1Score(task="multiclass", num_classes=num_classes)
        self.train_precision = Precision(task="multiclass", num_classes=num_classes)
        self.train_recall = Recall(task="multiclass", num_classes=num_classes)

        self.val_accuracy = Accuracy(task="multiclass", num_classes=num_classes)
        self.val_f1 = F1Score(task="multiclass", num_classes=num_classes)
        self.val_precision = Precision(task="multiclass", num_classes=num_classes)
        self.val_recall = Recall(task="multiclass", num_classes=num_classes)

    def forward(self, x):
        x = self.feature_extractor(x)
        x = self.classifier(x)
        return x

    def compute_metrics(self, logits, targets, prefix=""):
        """
        Вычисляет метрики по предсказаниям и целевым значениям.
        Логиты сначала преобразуются в предсказания с помощью argmax.

        Args:
            logits (Tensor): Выход модели.
            targets (Tensor): Целевые метки.
            prefix (str): Префикс, определяющий, для какого этапа считаем метрики ('train' или 'val').

        Returns:
            dict: Словарь с loss и вычисленными метриками.
        """
        loss = self.criterion(logits, targets)
        preds = torch.argmax(logits, dim=1)
        if prefix == "train":
            acc = self.train_accuracy(preds, targets)
            f1 = self.train_f1(preds, targets)
            prec = self.train_precision(preds, targets)
            rec = self.train_recall(preds, targets)
        else:  # validation
            acc = self.val_accuracy(preds, targets)
            f1 = self.val_f1(preds, targets)
            prec = self.val_precision(preds, targets)
            rec = self.val_recall(preds, targets)
        return {
            "loss": loss,
            "acc": acc,
            "f1": f1,
            "precision": prec,
            "recall": rec
        }

    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        metrics = self.compute_metrics(logits, y, prefix="train")
        self.log_dict({f"train_{k}": v for k, v in metrics.items()},
                      on_step=False, on_epoch=True, prog_bar=True)
        return metrics["loss"]

    def validation_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        metrics = self.compute_metrics(logits, y, prefix="val")
        self.log_dict({f"val_{k}": v for k, v in metrics.items()},
                      on_step=False, on_epoch=True, prog_bar=True)
        return metrics["loss"]

    def cosine_annealing_scheduler(self, optimizer):
        return torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=30)

    def configure_optimizers(self):
        optimizer = self.hparams.optimizer_cls(self.parameters(), lr=self.hparams.lr, **self.optimizer_params)
        scheduler = self.cosine_annealing_scheduler(optimizer)
        return {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": scheduler,
                "interval": "epoch",
                "frequency": 1
            }
        }

model = CNN(
    kernel_size=(3, 3),
    conv_filters=[32, 64, 128],
    num_classes=10,
    input_channels=3,
    lr=1e-3,
    dropout=0.3
)
wandb_logger = pl.loggers.WandbLogger(
        )

trainer = pl.Trainer(
        max_epochs=15,
        logger=wandb_logger,
        accelerator="auto",
        devices=1,
        callbacks=[
            pl.callbacks.EarlyStopping(
                monitor="val_loss",
                patience=5,
                mode="min"
            )
        ],
        gradient_clip_val=1.0,
        enable_progress_bar=True,
        check_val_every_n_epoch=1,
    )
trainer.fit(model, trainloader, testloader)

dataset = load_dataset('Marxulia/asl_sign_languages_alphabets_v03')

dataset

IMG_SIZE = (32, 32)

MEAN = [0.485, 0.456, 0.406]
STD = [0.229, 0.224, 0.225]

train_transforms = T.Compose([
    T.Resize(IMG_SIZE),
    T.RandomHorizontalFlip(),
    T.RandomRotation(10),
    T.ToTensor(),
    T.Normalize(MEAN, STD)
])

val_test_transforms = T.Compose([
    T.Resize(IMG_SIZE),
    T.ToTensor(),
    T.Normalize(MEAN, STD)])

class ImageDataset(Dataset):
    def __init__(self, hf_dataset, transform=None):
        """
        Args:
            hf_dataset: Загруженный датасет Hugging Face (один сплит, например, train).
            transform (callable, optional): Трансформации, которые будут применены к изображению.
        """
        self.hf_dataset = hf_dataset
        self.transform = transform
        self.image_column = 'image'
        self.label_column = 'label'

    def __len__(self):
        return len(self.hf_dataset)

    def __getitem__(self, idx):
        item = self.hf_dataset[idx]
        image = item[self.image_column]
        if self.transform:
            image = self.transform(image)
        label = item[self.label_column]
        label = torch.tensor(label, dtype=torch.long)
        return image, label

dataset = ImageDataset(dataset['train'], transform=train_transforms)

train_dataset,test_dataset = random_split(dataset,[0.8,0.2])
train_loader, test_loader = DataLoader(train_dataset),DataLoader(test_dataset)

filters = [[32,64,128],[64,128,256]]
kernel_sizes = [(5,5)]
batch_sizes = [64, 128]
flatten_sizes = [[512,256,128,64],[256,128,64]]
configs = []
for kernel_size in kernel_sizes:
    for filter in filters:
        for batch_size in batch_sizes:
            for flatten_size in flatten_sizes:
                configs.append((filter, kernel_size, batch_size, flatten_size))

configs

def train_experiment(kernel_size, filter, batch_size, flatten_size):
    wandb.init(
        project="ASL_(5,5)",
        group=f"kernel_size_{kernel_size}",
        name=f"filter_{filter[0]}_bs_{batch_size}_kernel_size_{kernel_size}_flatten_size_{flatten_size[0]}",
        config={
            "batch_size": batch_size,
            "kernel_size": kernel_size,
            "filter": filter
        }
    )

    model = CNN(
      kernel_size=kernel_size,
      conv_filters=filter,
      num_classes=29,
      input_channels=3,
      lr=1e-4,
      dropout=0.3,
      dense_layers = flatten_size
  )

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=4,
        pin_memory=True,
        persistent_workers=True
    )

    val_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=4,
        pin_memory=True,
        persistent_workers=True
    )

    wandb_logger = pl.loggers.WandbLogger(
        log_every_n_steps=0
        )

    trainer = pl.Trainer(
        max_epochs=30,
        logger=wandb_logger,
        accelerator="auto",
        devices=1,
        callbacks=[
            pl.callbacks.EarlyStopping(
                monitor="val_loss",
                patience=5,
                mode="min"
            )
        ],
        gradient_clip_val=1.0,
        enable_progress_bar=True,
        check_val_every_n_epoch=1,
    )

    try:
        trainer.fit(model, train_loader, val_loader)
    except Exception as e:
        print(f"Ошибка в эксперименте kernel_size={kernel_size}, filter={filter[0]}: {str(e)}")
    finally:
        wandb.finish()

for filter,kernel_size,batch_size, flatten_size in configs:
  train_experiment(kernel_size = kernel_size,filter=filter,batch_size = batch_size, flatten_size = flatten_size)