# -*- coding: utf-8 -*-
"""codeT5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HkKdCRalGRTjrojEIXxkrGMrN7Ji3MTB
"""

!pip install -q transformers datasets

!pip install -q pytorch-lightning wandb

from datasets import load_dataset

from datasets import  DatasetDict
train_dataset = load_dataset("code_x_glue_ct_code_to_text", "ruby", split="train[:1000]")
test_dataset = load_dataset("code_x_glue_ct_code_to_text", "ruby", split="test[:2000]")
validation_dataset = load_dataset("code_x_glue_ct_code_to_text", "ruby", split="validation[:200]")

dataset = DatasetDict({
    'train': train_dataset,
    'validation': validation_dataset,
    'test': test_dataset
})


print(dataset)

from transformers import RobertaTokenizer

tokenizer = RobertaTokenizer.from_pretrained("Salesforce/codet5-small")

prefix = "Summarize Ruby: "
max_input_length = 256
max_target_length = 128

def preprocess_examples(examples):
  codes = examples['code']
  docstrings = examples['docstring']

  inputs = [prefix + code for code in codes]
  model_inputs = tokenizer(inputs, max_length=max_input_length, padding="max_length", truncation=True)

  labels = tokenizer(docstrings, max_length=max_target_length, padding="max_length", truncation=True).input_ids
  labels_with_ignore_index = []
  for labels_example in labels:
    labels_example = [label if label != 0 else -100 for label in labels_example]
    labels_with_ignore_index.append(labels_example)

  model_inputs["labels"] = labels_with_ignore_index

  return model_inputs

dataset = dataset.map(preprocess_examples, batched=True)

from torch.utils.data import DataLoader

dataset.set_format(type="torch", columns=['input_ids', 'attention_mask', 'labels'])
train_dataloader = DataLoader(dataset['train'], shuffle=True, batch_size=8)
valid_dataloader = DataLoader(dataset['validation'], batch_size=8)
test_dataloader = DataLoader(dataset['test'], batch_size=4)

!pip install sacrebleu
import torch

from transformers import T5ForConditionalGeneration, AdamW, get_linear_schedule_with_warmup
import pytorch_lightning as pl
import sacrebleu

class CodeT5(pl.LightningModule):
    def __init__(self, lr=5e-5, num_train_epochs=7, warmup_steps=300):
        super().__init__()
        self.model = T5ForConditionalGeneration.from_pretrained("Salesforce/codet5-small")
        self.save_hyperparameters()

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        return outputs

    def common_step(self, batch, batch_idx):
        outputs = self(**batch)
        loss = outputs.loss
        return loss, outputs.logits

    def training_step(self, batch, batch_idx):
        loss, logits = self.common_step(batch, batch_idx)
        labels = batch["labels"]
        preds = torch.argmax(logits, dim=-1)
        bleu = sacrebleu.corpus_bleu(preds, labels)
        self.log("training_loss", loss, on_epoch=True)
        self.log("training_bleu", bleu.score, on_epoch=True)
        return loss

    def prediction_step(self, batch, batch_idx):
        loss, logits = self.common_step(batch, batch_idx)
        labels = batch["labels"]
        preds = torch.argmax(logits, dim=-1)
        bleu = sacrebleu.corpus_bleu(preds, labels)
        print("training_bleu", bleu.score)
        print(preds,'/n',labels)

    def validation_step(self, batch, batch_idx):
        loss, logits = self.common_step(batch, batch_idx)
        labels = batch["labels"]
        preds = torch.argmax(logits, dim=-1)
        bleu = sacrebleu.corpus_bleu(preds, labels)
        self.log("validation_loss", loss, on_epoch=True)
        self.log("validation_bleu", bleu.score, on_epoch=True)
        return loss

    def test_step(self, batch, batch_idx):
        loss, logits = self.common_step(batch, batch_idx)
        labels = batch["labels"]
        preds = torch.argmax(logits, dim=-1)
        bleu = sacrebleu.corpus_bleu(preds, labels)
        self.log("testing_loss", loss)
        self.log("testing_bleu", bleu.score)
        return loss

    def configure_optimizers(self):
        optimizer = AdamW(self.parameters(), lr=self.hparams.lr)
        num_train_optimization_steps = self.hparams.num_train_epochs * len(train_dataloader)
        lr_scheduler = {'scheduler': get_linear_schedule_with_warmup(optimizer,
                                                    num_warmup_steps=self.hparams.warmup_steps,
                                                    num_training_steps=num_train_optimization_steps),
                        'name': 'learning_rate',
                        'interval':'step',
                        'frequency': 1}

        return {"optimizer": optimizer, "lr_scheduler": lr_scheduler}

    def train_dataloader(self):
        return train_dataloader

    def val_dataloader(self):
        return valid_dataloader

    def test_dataloader(self):
        return test_dataloader

model = CodeT5()

trainer.validate(model)

trainer.test(model)

import matplotlib.pyplot as plt
learning_rates = lr_monitor.lrs
learning_rates = lr_monitor.lrs
print(learning_rates)
plt.figure(figsize=(10, 6))
plt.plot([i for i in range(len(learning_rates['learning_rate']))], learning_rates['learning_rate'], marker='o', color='b', linestyle='-')
plt.title('Learning Rate over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Learning Rate')

from transformers import AutoTokenizer
checkpoint = 'Salesforce/codet5-base'
tokenizer = AutoTokenizer.from_pretrained("Salesforce/codet5-small")

prefix = "Summarize Python: "
max_input_length = 256
max_target_length = 128

def preprocess_examples(examples):
  codes = examples['code']
  docstrings = examples['docstring']
  inputs = [prefix + code for code in codes]
  model_inputs = tokenizer(inputs,text_target = docstrings, max_length=max_input_length, padding="max_length", truncation=True)
  return model_inputs

from transformers import DataCollatorForSeq2Seq
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

dataset = dataset.map(preprocess_examples, batched=True)

from torch.utils.data import DataLoader

dataset.set_format(type="torch", columns=['input_ids', 'attention_mask', 'labels'])
train_dataloader = DataLoader(dataset['train'], shuffle=True, batch_size=8)
test_dataloader = DataLoader(dataset['test'], batch_size=4)

from transformers import T5ForConditionalGeneration, AdamW, get_linear_schedule_with_warmup
import pytorch_lightning as pl

class CodeT5(pl.LightningModule):
    def __init__(self, lr=5e-5, num_train_epochs=1, warmup_steps=200):
        super().__init__()
        self.model = T5ForConditionalGeneration.from_pretrained("Salesforce/codet5-small")
        self.save_hyperparameters()

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        return outputs

    def common_step(self, batch, batch_idx):
        outputs = self(**batch)
        loss = outputs.loss
        return loss

    def predict_step(self,  batch, batch_idx):
        loss = self.common_step(batch, batch_idx)
        self.log("precission_lost", loss)
        return loss

    def training_step(self, batch, batch_idx):
        loss = self.common_step(batch, batch_idx)
        self.log("training_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx):
        loss = self.common_step(batch, batch_idx)
        self.log("validation_loss", loss, on_epoch=True)
        return loss

    def test_step(self, batch, batch_idx):
        loss = self.common_step(batch, batch_idx)
        self.log("validation_loss", loss, on_epoch=True)
        return loss

    def configure_optimizers(self):
        optimizer = AdamW(self.parameters(), lr=self.hparams.lr)
        num_train_optimization_steps = self.hparams.num_train_epochs * len(train_dataloader)
        lr_scheduler = {'scheduler': get_linear_schedule_with_warmup(optimizer,
                                                    num_warmup_steps=self.hparams.warmup_steps,
                                                    num_training_steps=num_train_optimization_steps),
                        'name': 'learning_rate',
                        'interval':'step',
                        'frequency': 1}

        return {"optimizer": optimizer, "lr_scheduler": lr_scheduler}

    def train_dataloader(self):
        return train_dataloader

    def val_dataloader(self):
        return valid_dataloader

    def test_dataloader(self):
        return test_dataloader

model = CodeT5()

from pytorch_lightning.callbacks import RichProgressBar
from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBarTheme


progress_bar = RichProgressBar(
    theme=RichProgressBarTheme(
        description="green_yellow",
        progress_bar="green1",
        progress_bar_finished="green1",
        progress_bar_pulse="#6206E0",
        batch_progress="green_yellow",
        time="grey82",
        processing_speed="grey82",
        metrics="grey82",
    )
)

import wandb

wandb.login()

new_model = 'my_t5_small_test'
model = model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
training_args = Seq2SeqTrainingArguments(
    output_dir=new_model,
    overwrite_output_dir=True,
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=6,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=2,
    predict_with_generate=True,
    fp16=True
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

trainer.validate(model)