# -*- coding: utf-8 -*-
"""CodeBert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbwJ-uy_XSHMP8lSaPGa13Kyd1jYsgK8
"""

!pip install -q transformers datasets

! git clone -q https://github.com/microsoft/CodeXGLUE.git

from datasets import  DatasetDict
from datasets import load_dataset
train_dataset = load_dataset("code_x_glue_ct_code_to_text", "ruby", split="train[:2500]")
test_dataset = load_dataset("code_x_glue_ct_code_to_text", "ruby", split="test[:700]")
validation_dataset = load_dataset("code_x_glue_ct_code_to_text", "ruby", split="validation[:200]")
# Создание объекта DatasetDict и добавление загруженных наборов данных
dataset = DatasetDict({
    'train': train_dataset,
    'validation': validation_dataset,
    'test': test_dataset
})

import json
# Преобразуем данные в формат JSONL и сохраняем их в файлы
def save_data_to_jsonl(data, filename):
    with open(filename, 'w', encoding='utf-8') as f:
        for item in data:
            json.dump(item, f)
            f.write('\n')

# Создаем списки для тренировочных, тестовых и валидационных данных
train_data = dataset['train']
test_data = dataset['test']
validation_data = dataset['validation']

# Сохраняем данные в соответствующие файлы
save_data_to_jsonl(train_data, 'train.jsonl')
save_data_to_jsonl(test_data, 'test.jsonl')
save_data_to_jsonl(validation_data, 'validation.jsonl')

import pandas as pd

from dataclasses import dataclass
@dataclass
class ConfigurationModel:
	learning_rate : float
	batch_size : int
	beam : int
	test_file : str
	source_size : int
	target_size : int
	path_to_data_directory : str
	path_to_output_data_directory : str
	train_file : str
	dev_file : str
	count_epochs : int
	pretrained_model : str


configuration_codetext_model = ConfigurationModel(
	learning_rate = 5e-5,
	batch_size = 8,
	beam = 10,
	source_size = 256,
	target_size = 512,
	path_to_data_directory = '.',
	path_to_output_data_directory = 'model_for_java',
	train_file = '/content/train.jsonl',
	dev_file = '/content/validation.jsonl',
	test_file = '/content/test.jsonl',
	count_epochs = 6,
	pretrained_model = 'microsoft/codebert-base',
)
configuration_codetext_model

!python /content/CodeXGLUE/Code-Text/code-to-text/code/run.py \
	--do_train \
	--do_eval \
	--do_lower_case \
	--model_type roberta \
	--model_name_or_path {configuration_codetext_model.pretrained_model} \
	--train_filename {configuration_codetext_model.train_file} \
	--dev_filename {configuration_codetext_model.dev_file} \
	--output_dir {configuration_codetext_model.path_to_output_data_directory} \
	--max_source_length {configuration_codetext_model.source_size} \
	--max_target_length {configuration_codetext_model.target_size} \
	--beam_size {configuration_codetext_model.beam} \
	--train_batch_size {configuration_codetext_model.batch_size} \
	--eval_batch_size {configuration_codetext_model.batch_size} \
	--learning_rate {configuration_codetext_model.learning_rate} \
	--num_train_epochs {configuration_codetext_model.count_epochs}

binary_model_file = '/content/model_for_java/checkpoint-best-bleu/pytorch_model.bin'
!python  /content/CodeXGLUE/Code-Text/code-to-text/code/run.py \
    --do_test \
    --model_type roberta \
    --model_name_or_path microsoft/codebert-base \
    --load_model_path {binary_model_file} \
    --dev_filename {configuration_codetext_model.dev_file} \
    --test_filename {configuration_codetext_model.test_file} \
    --output_dir {configuration_codetext_model.path_to_output_data_directory} \
    --max_source_length {configuration_codetext_model.source_size} \
    --max_target_length {configuration_codetext_model.target_size} \
    --beam_size {configuration_codetext_model.beam} \
    --eval_batch_size {configuration_codetext_model.batch_size}

path_to_gold = '/content/model_for_java/dev.gold'
path_to_output = '/content/model_for_java/dev.output'

def read_result_txt_file(txt_file: str)-> list:
	with open(txt_file) as file:		return [' '.join(line.rstrip().replace('\t', ' ').split(' ')[1:]) for line in file]

#true comments and predicted
true_sent = read_result_txt_file(path_to_gold)
pred_sent = read_result_txt_file(path_to_output)
result_data_frame = pd.DataFrame(
    {
      'true' : true_sent,
      'pred' : pred_sent
    }
  )

for i in range(8):
  print('Correct:', result_data_frame['true'][i])
  print('Predicted', result_data_frame['pred'][i],'\n')
result_data_frame.head(10)